---
  - name: Ensure group {{ autograder_group }} exists
    ansible.builtin.group:
      name: "{{ autograder_group }}"
      state: present

  - name: Create {{ autograder_user }} runner user
    ansible.builtin.user:
      create_home: true
      name: "{{ autograder_user }}"
      group: "{{ autograder_group }}"
      shell: /bin/bash

  - name: Source Go binaries
    become_user: "{{ autograder_user }}"
    ansible.builtin.shell: source /etc/profile.d/go.sh
    args:
      executable: /bin/bash

  - name: Setup GOPATH for {{ autograder_user }}
    become_user: "{{ autograder_user }}"
    ansible.builtin.copy:
      content: |
        export GOPATH=$GOPATH:{{ autograder_home }}/go
        export PATH=$PATH:{{ autograder_home }}/go/bin
        export GO111MODULE=on
      dest: "{{ autograder_home }}/.bashrc"
      mode: 0644

  - name: Source GOPATH for {{ autograder_user }}
    become_user: "{{ autograder_user }}"
    ansible.builtin.shell: source "{{ autograder_home }}/.bashrc"
    args:
      executable: /bin/bash

  - name: Define GOPATH variable
    ansible.builtin.set_fact:
      GOPATH: "{{ autograder_home }}/go"
    when:
      - GOROOT is defined
      - GOPATH is not defined
  
  - name: Define GO111MODULE variable
    ansible.builtin.set_fact:
      GO111MODULE: "on"
    when: GO111MODULE is not defined

  # go deps
  - name: Install Go dependencies packages
    become: yes
    become_user: "{{ autograder_user }}"
    ansible.builtin.command: go get -u {{ item }}
    environment:
      GOROOT: "{{ GOROOT }}"
      GOPATH: "{{ GOPATH }}"
      GO111MODULE: "{{ GO111MODULE }}"
    with_items: "{{ go_dependencies }}"
    changed_when: false

  # grpcweb
  - name: Set facts for grpcweb package
    ansible.builtin.set_fact:
      grpcweb_bin: "{{ grpcweb_path }}/{{ protoc_grpcweb }}"
      protoc_grpcweb_url: "{{ grpcweb_repo }}/{{ grpcweb_version }}/{{ protoc_grpcweb }}-{{ grpcweb_version }}-{{ ansible_system }}-{{ ansible_machine }}"

  - name: Download grpcweb protoc plugin
    ansible.builtin.get_url:
      url: "{{ protoc_grpcweb_url }}"
      dest: "{{ grpcweb_bin }}"
      mode: '0440'

  - name: Ensure executable permission to grpcweb
    ansible.builtin.file:
      path: "{{ grpcweb_bin }}"
      state: touch
      mode: u+x,g+x

  # npm deps
  - name: Install webpack and typescript compiler
    community.general.npm:
      global: yes
      name: "{{ item }}"
    with_items:
      - typescript
      - webpack
      - webpack-cli
      - tslint
      - serve

  # quickfeed
  - name: Clone quickfeed source
    become: yes
    become_user: "{{ autograder_user }}"
    ansible.builtin.git:
      repo: "{{ quickfeed_repo }}"
      dest: "{{ quickfeed_root }}"
      version: "{{ quickfeed_branch }}"
      force: yes

  - name: Ensure permissions
    ansible.builtin.file:
      path: "{{ autograder_home }}"
      owner: "{{ autograder_user }}"
      group: "{{ autograder_group }}"
      recurse: yes

  - name: Build quickfeed source
    become_user: "{{ autograder_user }}"
    ansible.builtin.shell: "cd {{ quickfeed_root }} && make"
